name: Build WPF App

on:
  push:
    branches: [ master, develop ]
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Nerdbank.GitVersioning
        uses: dotnet/nbgv@v0.4
        id: nbgv

      - name: Show version
        run: echo "Version = ${{ steps.nbgv.outputs.SemVer2 }}"

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Show working directory
        run: pwd

      - name: Publish WPF App
        run: >
          dotnet publish ./PairTradingView.WpfApp/PairTradingView.WpfApp.csproj
          -c Release
          -p:Version=${{ steps.nbgv.outputs.SemVer2 }}
          -p:DebugType=None
          -p:DebugSymbols=false
          --self-contained:false

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: PairTradingView-${{ steps.nbgv.outputs.SemVer2 }}
          path: ./PairTradingView.WpfApp/bin/Release/net8.0-windows/publish/

